#!/bin/bash

set -e

if pacman -Qdqt; then
    pacman -Runs $(pacman -Qdqt)
fi
find "/usr/share/locale" -mindepth 1 -maxdepth 1 ! -name "en_US" ! -name "locale.alias" -exec rm -rf "{}" \;
rm -rf  \
    /tmp/*  \
    /usr/share/man/man*/*  \
    /var/cache/pacman/pkg/*  \
    /var/log/*  \
    /var/tmp/*
